// filepath: ibrfront/src/config/site.js
export const SITE_CONFIG = {
  name: "LBR Cleaning",
  tagline: "Professional Cleaning Services Across Nigeria",
  phone: "+234 801 234 5678",
  phoneDisplay: "+234 801 234 5678",
  email: "hello@lbrcleaning.com",
  supportEmail: "support@lbrcleaning.com",
  address: "Lagos, Nigeria",
  areas: ["Lagos", "Abuja", "Port Harcourt", "Ibadan", "Kaduna", "Enugu", "Calabar", "Benin City", "Kano", "Warri"],
  hours: {
    weekdays: "8:00 AM - 7:00 PM",
    saturday: "9:00 AM - 5:00 PM",
    sunday: "10:00 AM - 4:00 PM",
  },
  social: {
    instagram: "https://instagram.com/lbrcleaning",
    twitter: "https://twitter.com/lbrcleaning",
    facebook: "https://facebook.com/lbrcleaning",
    whatsapp: "https://wa.me/2348012345678",
  },
  currency: "NGN",
  currencySymbol: "₦",
};

export const SERVICES = [
  {
    id: "residential",
    title: "Residential Cleaning",
    shortTitle: "Home Cleaning",
    description: "Professional home cleaning for apartments, duplexes, and estates across Nigeria.",
    priceRange: "₦15,000 – ₦45,000",
    startingPrice: 15000,
    icon: "fa-solid fa-house",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=400&fit=crop",
    features: [
      "Living room vacuuming & dusting",
      "Bedroom cleaning & arrangement",
      "Bathroom and toilet scrubbing",
      "Kitchen surface wipe-down",
      "Window washing (interior)",
      "Trash collection and deodorizing",
    ],
    details:
      "Our residential cleaning service covers every room in your home. We use eco-friendly products that are safe for children, pets, and the environment. Whether you need a one-time deep clean or regular weekly service, our trained team delivers consistent, spotless results.",
  },
  {
    id: "commercial",
    title: "Office Cleaning",
    shortTitle: "Office Cleaning",
    description: "Hygienic workspace solutions for offices, co-working spaces, and corporate buildings across Nigeria.",
    priceRange: "₦25,000 – ₦80,000",
    startingPrice: 25000,
    icon: "fa-solid fa-briefcase",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop",
    features: [
      "Workstation sanitization",
      "Restroom deep cleaning",
      "Breakroom cleanup",
      "Floor mopping and vacuuming",
      "Reception and common area maintenance",
      "Customizable daily/weekly schedules",
    ],
    details:
      "A clean office is a productive office. Our commercial cleaning service ensures your workspace meets the highest hygiene standards. We work around your schedule — early morning, during lunch, or after hours — to minimize disruption to your business.",
  },
  {
    id: "deep_cleaning",
    title: "Deep Cleaning",
    shortTitle: "Deep Cleaning",
    description: "Intensive, top-to-bottom cleaning for spaces that need extra attention.",
    priceRange: "₦30,000 – ₦70,000",
    startingPrice: 30000,
    icon: "fa-solid fa-spray-can",
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&h=400&fit=crop",
    features: [
      "Behind appliances and furniture",
      "Wall and ceiling dusting",
      "Grout and tile scrubbing",
      "Light fixture cleaning",
      "Baseboard and door frame detailing",
      "Complete sanitization of high-touch areas",
    ],
    details:
      "Deep cleaning goes beyond the surface. We tackle the dirt and grime that regular cleaning misses — behind appliances, inside cabinets, and on high surfaces. Perfect for spring cleaning, move-ins, or spaces that haven't been professionally cleaned in a while.",
  },
  {
    id: "move_in_move_out",
    title: "Move In/Out Cleaning",
    shortTitle: "Move Cleaning",
    description: "Thorough cleaning for tenants moving in or out of a property.",
    priceRange: "₦35,000 – ₦60,000",
    startingPrice: 35000,
    icon: "fa-solid fa-truck-moving",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop",
    features: [
      "Inside cabinets and drawers",
      "Inside oven and refrigerator",
      "Wall spot cleaning",
      "Window interior and frames",
      "Floor stripping and waxing",
      "Final inspection checklist",
    ],
    details:
      "Moving is stressful enough. Our move-in/move-out cleaning ensures you get your full security deposit back and your new place feels like home from day one. We clean every nook, cranny, and hidden corner so the property is spotless.",
  },
  {
    id: "post_construction",
    title: "Post-Construction Cleaning",
    shortTitle: "Construction Cleanup",
    description: "Remove construction debris, dust, and prepare your space for occupancy.",
    priceRange: "₦45,000 – ₦120,000",
    startingPrice: 45000,
    icon: "fa-solid fa-building",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    features: [
      "Debris and dust removal",
      "Concrete and mortar cleanup",
      "Paint splatter removal",
      "Window and frame cleaning",
      "Floor polishing",
      "HVAC vent cleaning",
    ],
    details:
      "Construction leaves more than just a new build — it leaves dust everywhere. Our post-construction cleaning removes all traces of building work, making your space safe and ready for occupation. We handle residential and commercial projects of any size.",
  },
  {
    id: "carpet_cleaning",
    title: "Carpet Cleaning",
    shortTitle: "Carpet Cleaning",
    description: "Deep carpet cleaning that removes stains, odors, and allergens.",
    priceRange: "₦18,000 – ₦40,000",
    startingPrice: 18000,
    icon: "fa-solid fa-rug",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop",
    features: [
      "Pre-treatment of carpet surfaces",
      "Deep shampooing with safe solutions",
      "Stain and odor removal",
      "Fast-drying extraction",
      "Eco-friendly solutions",
      "Protective coating application",
    ],
    details:
      "Carpets trap dust, allergens, and stains that regular vacuuming can't remove. Our professional carpet cleaning uses hot water extraction and eco-friendly solutions to deep-clean your carpets, leaving them fresh, fluffy, and allergen-free.",
  },
  {
    id: "window_cleaning",
    title: "Window Cleaning",
    shortTitle: "Window Cleaning",
    description: "Streak-free window cleaning for homes and offices.",
    priceRange: "₦12,000 – ₦35,000",
    startingPrice: 12000,
    icon: "fa-solid fa-window-maximize",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&h=400&fit=crop",
    features: [
      "Interior and exterior window cleaning",
      "Frame and sill cleaning",
      "Screen cleaning",
      "Streak-free finish",
      "Hard water stain removal",
      "High-rise window cleaning available",
    ],
    details:
      "Clean windows transform the look of any space. We use professional-grade squeegees and eco-friendly glass cleaners to achieve a perfect, streak-free finish. We clean both interior and exterior surfaces, including frames, sills, and screens.",
  },
  {
    id: "sanitization",
    title: "Sanitization Service",
    shortTitle: "Sanitization",
    description: "Hospital-grade disinfection for homes, offices, and public spaces.",
    priceRange: "₦20,000 – ₦50,000",
    startingPrice: 20000,
    icon: "fa-solid fa-hand-sparkles",
    image: "https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=600&h=400&fit=crop",
    features: [
      "Hospital-grade disinfectants",
      "High-touch surface sanitization",
      "Fogging and misting available",
      "Post-COVID deep sanitization",
      "Air duct and vent sanitization",
      "Certificate of sanitization provided",
    ],
    details:
      "In a post-pandemic world, proper sanitization is non-negotiable. Our sanitization service uses hospital-grade disinfectants and professional fogging equipment to eliminate 99.9% of bacteria and viruses. We provide a certificate of sanitization for your records.",
  },
];

export const AREAS_SERVED = [
  "Lagos",
  "Abuja",
  "Port Harcourt",
  "Ibadan",
  "Kaduna",
  "Enugu",
  "Calabar",
  "Benin City",
  "Kano",
  "Warri",
];

export const WHATSAPP_NUMBER = "2348012345678";
